# ── Room geometry (from new_world.world) ──
# Outer walls: X[-1.0, 2.6], Y[-3.8, 1.0]
# L-shape notch in upper-left corner
# Internal obstacles at (~0.77, 0.67) and (~-0.75, 0.78)
# Room center ≈ (0.8, -1.4)

base_station:
  target_x: -0.3
  target_y: 0.0
  target_theta: 0.0
  runoff_risk: "Low"
  min_x: 0.3
  max_x: 1.3
  min_y: -1.9
  max_y: -0.9
  baseline_moisture: 50.0
  baseline_nutrients: 50.0

# #Green — Upper Left
# zone_0:
#   target_x: -0.4
#   target_y: 0.0
#   target_theta: 0.0
#   runoff_risk: "Low"
#   min_x: -0.9
#   max_x: 0.6
#   min_y: -0.5
#   max_y: 0.85
#   baseline_moisture: 50.0
#   baseline_nutrients: 20.0



#Green — Upper Left
zone_0:
  target_x: -0.65
  target_y: 0.8
  target_theta: 0.0
  runoff_risk: "Low"
  min_x: -1.5
  max_x: -0.1
  min_y: 0.5
  max_y: 1.2
  baseline_moisture: 50.0
  baseline_nutrients: 20.0


#Blue — Upper Right
zone_1:
  target_x: 0.8
  target_y: 0.7
  target_theta: 90.0
  runoff_risk: "High"
  min_x: 0.4
  max_x: 1.2
  min_y: 0.3
  max_y: 1.2
  baseline_moisture: 95.0
  baseline_nutrients: 30.0

#Yellow — Lower Right
zone_2:
  target_x: 0.8
  target_y: -1.0
  target_theta: 180.0
  runoff_risk: "Medium"
  min_x: 0.4
  max_x: 1.2
  min_y: -2.0
  max_y: -0.4
  baseline_moisture: 20.0
  baseline_nutrients: 80.0

#Red — Lower Left
zone_3:
  target_x: -0.7
  target_y: -1.0
  target_theta: 270.0
  runoff_risk: "High"
  min_x: -1.5
  max_x: 0.0
  min_y: -2.0
  max_y: -0.4
  baseline_moisture: 50.0
  baseline_nutrients: 45.0
